import type { Metadata } from "next";
import "./globals.css";
// import "@/fonts/neuedisplay.ttf";

export const metadata: Metadata = {
  title: "Sundown Studio",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/sun.png",
      href: "/sun.png",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
